server:
  port: 8099
spring:
  application:
    name: api-order-submit
  redis:
    port: 7001
    host: 43.142.150.193
    database: 0
  rabbitmq:
    host: 43.142.150.193
    port: 5672
    virtual-host: host1
    username: admin
    password: admin
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka

feign:
  hystrix:
    enabled: true
